"""add expected destination to payment intents

Revision ID: 16f0e5949e29
Revises: 1079d3c8efec
Create Date: 2026-06-10 09:31:08.652147

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f0e5949e29'
down_revision: str | None = '1079d3c8efec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('expected_destination', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_intents', 'expected_destination')
    # ### end Alembic commands ###
