"""add merchants and api keys

Revision ID: 237db2a44e88
Revises: 2b4aca4680b5
Create Date: 2026-06-12 18:09:36.195360

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "237db2a44e88"
down_revision: str | None = "2b4aca4680b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_slug"), "merchants", ["slug"], unique=True)
    op.create_table(
        "payment_intent_expirer_states",
        sa.Column("worker_name", sa.String(length=100), nullable=False),
        sa.Column("last_cycle_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("successful_cycles_total", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("failed_cycles_total", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "expired_payment_intents_total", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("worker_name"),
    )
    op.create_table(
        "merchant_api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("key_digest", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_api_keys_key_prefix"), "merchant_api_keys", ["key_prefix"], unique=True
    )
    op.create_index(
        op.f("ix_merchant_api_keys_merchant_id"), "merchant_api_keys", ["merchant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_merchant_api_keys_merchant_id"), table_name="merchant_api_keys")
    op.drop_index(op.f("ix_merchant_api_keys_key_prefix"), table_name="merchant_api_keys")
    op.drop_table("merchant_api_keys")
    op.drop_table("payment_intent_expirer_states")
    op.drop_index(op.f("ix_merchants_slug"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
