"""add payment intent cancellation details

Revision ID: 2b4aca4680b5
Revises: 98e95580d04a
Create Date: 2026-06-12 16:30:46.794604

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4aca4680b5'
down_revision: str | None = '98e95580d04a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_intent_expirer_states')
    op.add_column('payment_intents', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment_intents', sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_intents', 'cancellation_reason')
    op.drop_column('payment_intents', 'cancelled_at')
    op.create_table('payment_intent_expirer_states',
    sa.Column('worker_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_cycle_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_success_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('successful_cycles_total', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_cycles_total', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expired_payment_intents_total', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('worker_name', name=op.f('payment_intent_expirer_states_pkey'))
    )
    # ### end Alembic commands ###
