"""add payment intent idempotency

Revision ID: 5854ba396dcb
Revises: 6125f436db49
Create Date: 2026-06-12 14:15:25.414953

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5854ba396dcb"
down_revision: str | None = "6125f436db49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_intent_expirer_states")
    op.add_column(
        "payment_intents", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "payment_intents", sa.Column("idempotency_fingerprint", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_payment_intents_idempotency_key"),
        "payment_intents",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_intents_idempotency_key"), table_name="payment_intents")
    op.drop_column("payment_intents", "idempotency_fingerprint")
    op.drop_column("payment_intents", "idempotency_key")
    op.create_table(
        "payment_intent_expirer_states",
        sa.Column("worker_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "last_cycle_started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_success_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_error_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("last_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "successful_cycles_total",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "failed_cycles_total",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expired_payment_intents_total",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("worker_name", name=op.f("payment_intent_expirer_states_pkey")),
    )
    # ### end Alembic commands ###
